channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.1.2
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1
  - numpy==1.25.2
  - packaging==23.0
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.11.1
name: mlflow-env
